apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek-v2-lite-pvc
  labels:
    app: afd-recipe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
